### ISSUE TITLE
Wav Sound files not load

### ISSUE THREAD

**Issue by joelcnz** [BindBC/bindbc-sdl#18]
Using Mix_LoadWAV, files are found, but won't load!?

[Edit]

I've tried different versions. I have it initialized.

**Comment by mdparker** [comment]
This is not an SDL support forum, but a bug tracker for reporting issues with BindBC. Before reporting anything here, you should first determine as best you can if it is a program error, a problem with the binding, or a problem with the library so that you can go to the correct place for help.

"won't load" isn't enough information to help anyone help you. When you get an error return code from most SDL functions, you can use SDL_GetError to fetch an error string describing the problem. It returns a pointer to a static string, so you can get a D string from it with `std.string.fromStringz` (as long as you don't want to store it anywhere, it which case you'll want to use `std.conv.to` to make a copy).

```d
import std.string : fromStringz;
throw new Exception("Error trying to load wav file: " ~ SDL_GetError().fromStringz);
```

I would assume that this has nothing to do with the binding, though it's not impossible that there's a function signature mismatch causing wonky behavior.

**Comment by joelcnz** [comment]
Oh, thanks, the error message thing helped. I've never used 'fromStringz' before.
