### ISSUE TITLE
SDL Mutex and Thread

### ISSUE THREAD

**Issue by Kayomn** [BindBC/bindbc-sdl#21]
It appears as though the modules for SDL_Thread and SDL_Mutex are missing from these bindings.

Is there a reason why they're not exposed?

**Comment by mdparker** [comment]
Yes, primarily because D already has multithreading support in the standard library, so that meant less work for me. I never included them in Derelict either, and no one has ever requested them. I do realize if anyone wants to do multithreading with `-betterC`, then they will be useful. Is that your situation?

**Comment by Kayomn** [comment]
Yeah, currently I'm working on a betterC projecting using SDL and wanted to avoid relying on POSIX threads and instead use a dependency I already have.

**Comment by mdparker** [comment]
Okay. I finally got around to implementing both headers. I also implemented `SDL_atomic.h`, though that one was a bit troublesome. It currently brings in a dependency on a template in `core.atomic` even in BetterC mode, but no linking required. I already have a dependency on `core.stdc.config` in some of these modules, so this is nothing new. One day, if anyone needs to build this on a machine where there's no DRuntime available, then I'll see about eliminating the dependencies, but until then it's no big deal.

It's all available in v0.19.0. Please report file new issues for any bugs you encounter with the new stuff. Thanks!
