### ISSUE TITLE
SDL 3.1 preview support?

### ISSUE THREAD

**Issue by Herringway** [BindBC/bindbc-sdl#62]
The [SDL 3.1 preview](https://github.com/libsdl-org/SDL/releases/tag/prerelease-3.1.0) was released today. Although the ABI hasn't been declared totally stable yet, it seems safe to say things won't change too dramatically for the stable release at this point. I would like to see some support for 3.x so that I can start testing things out in my own projects.

**Comment by ichordev** [comment]
SDL 3.0 support will permanently replace SDL 2.0 support. It won't be quick for me to make the bindings, because I'll be rewriting all of them from scratch. The D-side API will probably also independently change significantly, although I'm not quite sure how at this juncture. I'm not ruling it out, but also not prioritising doing this until SDL 3.0 is fully released because nothing even supports it yet—it's not available via any package managers even.

**Comment by ichordev** [comment]
All future pull requests for SDL2 support should be in the [SDL2](https://github.com/BindBC/bindbc-sdl/tree/SDL2) branch, as ~master is now moving towards supporting SDL3 exclusively.

**Comment by ichordev** [comment]
Since stable ABI support has been announced, I'd like to get the ball rolling on this again.

Be warned: if SDL 3.1.3 support is finished before the stable SDL 3.2.0 release, it will be *replaced* by SDL 3.2.X support in the future. This *shouldn't* mean anything since 3.1.3 is *supposed* to be ABI stable, but if there are any differences then just know that I won't be maintaining 3.1 support separately—you'll have to upgrade to 3.2.

First version of 3.0 is 3.2... so confusing. 🤦‍♀️

**Comment by ichordev** [comment]
The sneaky bastards have deleted the old prerelease tag, so I have to start the bindings from scratch again wohoo…

**Comment by ichordev** [comment]
The core bindings are almost 'done' & ready for me to test.

**Comment by ichordev** [comment]
Core bindings ‘done’. Now they need to be thoroughly tested. I’ll tag `v2.0.0-prerelease` once I’ve done some housekeeping later today.

**Comment by ichordev** [comment]
I have released `v2.0.0-prerelease`. Please test it and open issues if you find any problems! :)
